<?php

/**
 * Discussify
 * 
 * Version: 0.1.0
 * 
 * by Sam Wilcox <sam@discussify.com>
 * https://www.discussify.com
 * 
 * User-End License Agreement:
 * https://license.discussify.com
 */

// This file may not be accessed directly.
if (!defined('APP_ACTIVE')) {
    \header(isset($_SERVER['SERVER_PROTOCOL']) ? $_SERVER['SERVER_PROTOCOL'] : 'HTTP/1.0 forbidden');
    exit(1);
}

// Database connection information.
// Generated by Discussify Installer.

$cfg['db_driver'] = 'mysqli';
$cfg['db_host'] = 'localhost';
$cfg['db_port'] = 3306;
$cfg['db_username'] = 'root';
$cfg['db_password'] = '1Trouble7!';
$cfg['db_name'] = 'discussify';
$cfg['db_prefix'] = '';